/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as IdleRouteImport } from './routes/idle'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as SatelliteMapRouteImport } from './routes/satellite-map'
import { Route as VoyageRouteImport } from './routes/voyage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const IdleRoute = IdleRouteImport.update({
  id: '/idle',
  path: '/idle',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const SatelliteMapRoute = SatelliteMapRouteImport.update({
  id: '/satellite-map',
  path: '/satellite-map',
  getParentRoute: () => rootRouteImport,
} as any)
const VoyageRoute = VoyageRouteImport.update({
  id: '/voyage',
  path: '/voyage',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forecast': typeof ForecastRoute
  '/idle': typeof IdleRoute
  '/risk': typeof RiskRoute
  '/satellite-map': typeof SatelliteMapRoute
  '/voyage': typeof VoyageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forecast': typeof ForecastRoute
  '/idle': typeof IdleRoute
  '/risk': typeof RiskRoute
  '/satellite-map': typeof SatelliteMapRoute
  '/voyage': typeof VoyageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forecast': typeof ForecastRoute
  '/idle': typeof IdleRoute
  '/risk': typeof RiskRoute
  '/satellite-map': typeof SatelliteMapRoute
  '/voyage': typeof VoyageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/forecast' | '/idle' | '/risk' | '/satellite-map' | '/voyage'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/forecast' | '/idle' | '/risk' | '/satellite-map' | '/voyage'
  id:
    | '__root__'
    | '/'
    | '/forecast'
    | '/idle'
    | '/risk'
    | '/satellite-map'
    | '/voyage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForecastRoute: typeof ForecastRoute
  IdleRoute: typeof IdleRoute
  RiskRoute: typeof RiskRoute
  SatelliteMapRoute: typeof SatelliteMapRoute
  VoyageRoute: typeof VoyageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idle': {
      id: '/idle'
      path: '/idle'
      fullPath: '/idle'
      preLoaderRoute: typeof IdleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/satellite-map': {
      id: '/satellite-map'
      path: '/satellite-map'
      fullPath: '/satellite-map'
      preLoaderRoute: typeof SatelliteMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voyage': {
      id: '/voyage'
      path: '/voyage'
      fullPath: '/voyage'
      preLoaderRoute: typeof VoyageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForecastRoute: ForecastRoute,
  IdleRoute: IdleRoute,
  RiskRoute: RiskRoute,
  SatelliteMapRoute: SatelliteMapRoute,
  VoyageRoute: VoyageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
